// 1) EASY RESUME DATA IN JSON FARMAT

let resume = {
  Name: "MOHAMED SHAKIL",
  DOB: "21.08.2003",
  Gender: "Male",
  Nationality: "INDIAN",
  Maried_status: "Single",
  Languages_known: ["Tamil" , "English"],
  Degree: "B.com - ACTURAIAL MANAGEMENT",
  University_board: "Dr G R DAMODARAN COLLEGE OF SCIENCE",
  Percentage_CGPA: "62%",
  Year_of_passing: 2024,
  Experience: "FRESHER",
};
console.log(resume);
